package org.irdresearch.tbreach.shared.model;

import java.util.Date;

// default package
// Generated Dec 21, 2010 3:45:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * Feedback generated by hbm2java
 */
public class Dictionary implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 6170013251205552269L;
	private Long				termId;
	private String				term;
	private String				definition;
	private Date				enteredOn;
	private String				definedBy;
	private Date				lastRevised;
	private String				revisedBy;
	private String				previousDefinition;
	private String				originalDefinition;

	public Dictionary()
	{
		// Not implemented
	}

	public Dictionary(String term, String definition, Date enteredOn, String definedBy)
	{
		this.term = term;
		this.definition = definition;
		this.enteredOn = enteredOn;
		this.definedBy = definedBy;
	}

	public Long getTermId()
	{
		return termId;
	}

	public void setTermId(Long termId)
	{
		this.termId = termId;
	}

	public String getTerm()
	{
		return term;
	}

	public void setTerm(String term)
	{
		this.term = term;
	}

	public String getDefinition()
	{
		return definition;
	}

	public void setDefinition(String definition)
	{
		this.definition = definition;
	}

	public Date getEnteredOn()
	{
		return enteredOn;
	}

	public void setEnteredOn(Date enteredOn)
	{
		this.enteredOn = enteredOn;
	}

	public String getDefinedBy()
	{
		return definedBy;
	}

	public void setDefinedBy(String definedBy)
	{
		this.definedBy = definedBy;
	}

	public Date getLastRevised()
	{
		return lastRevised;
	}

	public void setLastRevised(Date lastRevised)
	{
		this.lastRevised = lastRevised;
	}

	public String getRevisedBy()
	{
		return revisedBy;
	}

	public void setRevisedBy(String revisedBy)
	{
		this.revisedBy = revisedBy;
	}

	public String getPreviousDefinition()
	{
		return previousDefinition;
	}

	public void setPreviousDefinition(String previousDefinition)
	{
		this.previousDefinition = previousDefinition;
	}

	public String getOriginalDefinition()
	{
		return originalDefinition;
	}

	public void setOriginalDefinition(String originalDefinition)
	{
		this.originalDefinition = originalDefinition;
	}

	@Override
	public String toString()
	{
		return termId + ", " + term + ", " + definition + ", " + enteredOn + ", " + definedBy + ", " + lastRevised + ", " + revisedBy + ", "
				+ previousDefinition + ", " + originalDefinition;
	}
}
