
package org.irdresearch.tbreach.shared.model;

// Generated Dec 1, 2011 12:43:27 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * DrugHistory generated by hbm2java
 */
public class DrugHistory implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -1848460477396051564L;
	private DrugHistoryId	id;
	private Date			dateDispensed;
	private String			drugsDeliveredTo;
	private String			periodType;
	private int				pillsDelivered;
	private int				pillsQuotaDelivered;
	private int				streptomycinDelivered;
	private int				streptomycinQuotaDelivered;
	private int				syrupDelivered;
	private int				syrupQuotaDelivered;

	public DrugHistory ()
	{
		// Not implemented
	}

	public DrugHistory (DrugHistoryId id, Date dateDispensed, int pillsDelivered, int pillsQuotaDelivered, int streptomycinDelivered, int streptomycinQuotaDelivered, int syrupDelivered,
			int syrupQuotaDelivered)
	{
		this.id = id;
		this.dateDispensed = dateDispensed;
		this.pillsDelivered = pillsDelivered;
		this.pillsQuotaDelivered = pillsQuotaDelivered;
		this.streptomycinDelivered = streptomycinDelivered;
		this.streptomycinQuotaDelivered = streptomycinQuotaDelivered;
		this.syrupDelivered = syrupDelivered;
		this.syrupQuotaDelivered = syrupQuotaDelivered;
	}

	public DrugHistory (DrugHistoryId id, Date dateDispensed, String drugsDeliveredTo, String periodType, int pillsDelivered, int pillsQuotaDelivered, int streptomycinDelivered,
			int streptomycinQuotaDelivered, int syrupDelivered, int syrupQuotaDelivered)
	{
		this.id = id;
		this.dateDispensed = dateDispensed;
		this.drugsDeliveredTo = drugsDeliveredTo;
		this.periodType = periodType;
		this.pillsDelivered = pillsDelivered;
		this.pillsQuotaDelivered = pillsQuotaDelivered;
		this.streptomycinDelivered = streptomycinDelivered;
		this.streptomycinQuotaDelivered = streptomycinQuotaDelivered;
		this.syrupDelivered = syrupDelivered;
		this.syrupQuotaDelivered = syrupQuotaDelivered;
	}

	public DrugHistoryId getId ()
	{
		return this.id;
	}

	public void setId (DrugHistoryId id)
	{
		this.id = id;
	}

	public Date getDateDispensed ()
	{
		return this.dateDispensed;
	}

	public void setDateDispensed (Date dateDispensed)
	{
		this.dateDispensed = dateDispensed;
	}

	public String getDrugsDeliveredTo ()
	{
		return this.drugsDeliveredTo;
	}

	public void setDrugsDeliveredTo (String drugsDeliveredTo)
	{
		this.drugsDeliveredTo = drugsDeliveredTo;
	}

	public String getPeriodType ()
	{
		return this.periodType;
	}

	public void setPeriodType (String periodType)
	{
		this.periodType = periodType;
	}

	public int getPillsDelivered ()
	{
		return this.pillsDelivered;
	}

	public void setPillsDelivered (int pillsDelivered)
	{
		this.pillsDelivered = pillsDelivered;
	}

	public int getPillsQuotaDelivered ()
	{
		return this.pillsQuotaDelivered;
	}

	public void setPillsQuotaDelivered (int pillsQuotaDelivered)
	{
		this.pillsQuotaDelivered = pillsQuotaDelivered;
	}

	public int getStreptomycinDelivered ()
	{
		return this.streptomycinDelivered;
	}

	public void setStreptomycinDelivered (int streptomycinDelivered)
	{
		this.streptomycinDelivered = streptomycinDelivered;
	}

	public int getStreptomycinQuotaDelivered ()
	{
		return this.streptomycinQuotaDelivered;
	}

	public void setStreptomycinQuotaDelivered (int streptomycinQuotaDelivered)
	{
		this.streptomycinQuotaDelivered = streptomycinQuotaDelivered;
	}

	public int getSyrupDelivered ()
	{
		return this.syrupDelivered;
	}

	public void setSyrupDelivered (int syrupDelivered)
	{
		this.syrupDelivered = syrupDelivered;
	}

	public int getSyrupQuotaDelivered ()
	{
		return this.syrupQuotaDelivered;
	}

	public void setSyrupQuotaDelivered (int syrupQuotaDelivered)
	{
		this.syrupQuotaDelivered = syrupQuotaDelivered;
	}

	@Override
	public String toString()
	{
		return id + ", " + dateDispensed + ", " + drugsDeliveredTo + ", " + periodType + ", " + pillsDelivered + ", " + pillsQuotaDelivered + ", "
				+ streptomycinDelivered + ", " + streptomycinQuotaDelivered + ", " + syrupDelivered + ", " + syrupQuotaDelivered;
	}
}
