
package org.irdresearch.tbreach.shared.model;

// Generated Dec 1, 2011 12:43:27 PM by Hibernate Tools 3.4.0.Beta1

/**
 * DrugHistoryId generated by hbm2java
 */
public class DrugHistoryId implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 1643303668617505211L;
	private String	patientId;
	private int		dispensationNo;

	public DrugHistoryId ()
	{
		// Not implemented
	}

	public DrugHistoryId (String patientId, int dispensationNo)
	{
		this.patientId = patientId;
		this.dispensationNo = dispensationNo;
	}

	public String getPatientId ()
	{
		return this.patientId;
	}

	public void setPatientId (String patientId)
	{
		this.patientId = patientId;
	}

	public int getDispensationNo ()
	{
		return this.dispensationNo;
	}

	public void setDispensationNo (int dispensationNo)
	{
		this.dispensationNo = dispensationNo;
	}

	public boolean equals (Object other)
	{
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DrugHistoryId))
			return false;
		DrugHistoryId castOther = (DrugHistoryId) other;

		return ((this.getPatientId () == castOther.getPatientId ()) || (this.getPatientId () != null && castOther.getPatientId () != null && this.getPatientId ().equals (castOther.getPatientId ())))
				&& (this.getDispensationNo () == castOther.getDispensationNo ());
	}

	public int hashCode ()
	{
		int result = 17;

		result = 37 * result + (getPatientId () == null ? 0 : this.getPatientId ().hashCode ());
		result = 37 * result + this.getDispensationNo ();
		return result;
	}

	@Override
	public String toString()
	{
		return patientId + ", " + dispensationNo;
	}

}
