// default package
// Generated Dec 30, 2010 3:31:23 PM by Hibernate Tools 3.4.0.Beta1
package org.irdresearch.tbreach.shared.model;

/**
 * Gpmapping generated by hbm2java
 */
public class GpMapping implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -1510397310288304837L;
	private GpMappingId			id;

	public GpMapping()
	{
		// Not implemented
	}

	public GpMapping(GpMappingId id)
	{
		this.id = id;
	}

	public GpMappingId getId()
	{
		return this.id;
	}

	public void setId(GpMappingId id)
	{
		this.id = id;
	}

	@Override
	public String toString()
	{
		return id.toString();
	}
}
