package org.irdresearch.tbreach.shared.model;

// Generated Mar 14, 2011 5:54:08 PM by Hibernate Tools 3.4.0.CR1

/**
 * HouseholdId generated by hbm2java
 */
public class HouseholdId implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -6392094597133307175L;
	private String				patientMrno;
	private String				householdId;

	public HouseholdId()
	{
		// Not implemented
	}

	public HouseholdId(String patientMrno, String householdId)
	{
		this.patientMrno = patientMrno;
		this.householdId = householdId;
	}

	public String getPatientMrno()
	{
		return this.patientMrno;
	}

	public void setPatientMrno(String patientMrno)
	{
		this.patientMrno = patientMrno;
	}

	public String getHouseholdId()
	{
		return this.householdId;
	}

	public void setHouseholdId(String householdId)
	{
		this.householdId = householdId;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		return this.patientMrno + ", " + this.householdId;
	}

}
