package org.irdresearch.tbreach.shared.model;

// Generated Mar 14, 2011 5:54:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Household generated by hbm2java
 */
public class Household implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -3306876094352824365L;
	private HouseholdId			id;
	private String				relationship;
	private String				fullName;
	private String				guardianName;
	private char				gender;
	private Date				dateEncountered;
	private Date				dob;
	private boolean				screened;
	private Date				dateEntered;
	private String				details;

	public Household()
	{
		// Not implemented
	}

	public Household(HouseholdId id, String relationship, String fullName, char gender, Date dob, boolean screened, Date dateEntered)
	{
		this.id = id;
		this.relationship = relationship;
		this.fullName = fullName;
		this.gender = gender;
		this.dob = dob;
		this.screened = screened;
		this.dateEntered = dateEntered;
	}

	public Household(HouseholdId id, String relationship, String fullName, String guardianName, char gender, Date dob, boolean screened,
			Date dateEntered, String details)
	{
		this.id = id;
		this.relationship = relationship;
		this.fullName = fullName;
		this.guardianName = guardianName;
		this.gender = gender;
		this.dob = dob;
		this.screened = screened;
		this.dateEntered = dateEntered;
		this.details = details;
	}

	public HouseholdId getId()
	{
		return this.id;
	}

	public void setId(HouseholdId id)
	{
		this.id = id;
	}

	public String getRelationship()
	{
		return this.relationship;
	}

	public void setRelationship(String relationship)
	{
		this.relationship = relationship;
	}

	public String getFullName()
	{
		return this.fullName;
	}

	public void setFullName(String fullName)
	{
		this.fullName = fullName;
	}

	public String getGuardianName()
	{
		return this.guardianName;
	}

	public void setGuardianName(String guardianName)
	{
		this.guardianName = guardianName;
	}

	public char getGender()
	{
		return this.gender;
	}

	public void setGender(char gender)
	{
		this.gender = gender;
	}

	public Date getDateEncountered()
	{
		return dateEncountered;
	}

	public void setDateEncountered(Date dateEncountered)
	{
		this.dateEncountered = dateEncountered;
	}

	public Date getDob()
	{
		return this.dob;
	}

	public void setDob(Date dob)
	{
		this.dob = dob;
	}

	public boolean isScreened()
	{
		return this.screened;
	}

	public void setScreened(boolean screened)
	{
		this.screened = screened;
	}

	public Date getDateEntered()
	{
		return this.dateEntered;
	}

	public void setDateEntered(Date dateEntered)
	{
		this.dateEntered = dateEntered;
	}

	public String getDetails()
	{
		return this.details;
	}

	public void setDetails(String details)
	{
		this.details = details;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		return this.id + ", " + this.relationship + ", " + this.fullName + ", " + this.guardianName + ", " + this.gender + ", " + this.dob + ", "
				+ this.screened + ", " + this.dateEntered + ", " + this.details;
	}

}
