package org.irdresearch.tbreach.shared.model;

// default package
// Generated Dec 21, 2010 3:45:59 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * Incentive generated by hbm2java
 */
public class Incentive implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= -8268776818272049545L;
	private IncentiveId			id;
	private String				mode;
	private Date				dateTransferred;
	private String				status;
	private String				remarks;

	public Incentive()
	{
		// Not implemented
	}

	public Incentive(IncentiveId id, Date dateTransferred, String status)
	{
		this.id = id;
		this.dateTransferred = dateTransferred;
		this.status = status;
	}

	public Incentive(IncentiveId id, String mode, Date dateTransferred, String status, String remarks)
	{
		this.id = id;
		this.mode = mode;
		this.dateTransferred = dateTransferred;
		this.status = status;
		this.remarks = remarks;
	}

	public IncentiveId getId()
	{
		return this.id;
	}

	public void setId(IncentiveId id)
	{
		this.id = id;
	}

	public String getMode()
	{
		return this.mode;
	}

	public void setMode(String mode)
	{
		this.mode = mode;
	}

	public Date getDateTransferred()
	{
		return this.dateTransferred;
	}

	public void setDateTransferred(Date dateTransferred)
	{
		this.dateTransferred = dateTransferred;
	}

	public String getStatus()
	{
		return this.status;
	}

	public void setStatus(String status)
	{
		this.status = status;
	}

	public String getRemarks()
	{
		return this.remarks;
	}

	public void setRemarks(String remarks)
	{
		this.remarks = remarks;
	}

	@Override
	public String toString()
	{
		return id + ", " + mode + ", " + dateTransferred + ", " + status + ", " + remarks;
	}

}
