package org.irdresearch.tbreach.shared.model;

// default package
// Generated Dec 21, 2010 3:45:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * Monitor generated by hbm2java
 */
public class Monitor implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 8416441906592370787L;
	private String				monitorId;
	private String				supervisorId;

	public Monitor()
	{
		// Not implemented
	}

	public Monitor(String monitorId, String supervisorId)
	{
		this.monitorId = monitorId;
		this.supervisorId = supervisorId;
	}

	public String getMonitorId()
	{
		return this.monitorId;
	}

	public void setMonitorId(String monitorId)
	{
		this.monitorId = monitorId;
	}

	public String getSupervisorId()
	{
		return this.supervisorId;
	}

	public void setSupervisorId(String supervisorId)
	{
		this.supervisorId = supervisorId;
	}

	@Override
	public String toString()
	{
		return monitorId + ", " + supervisorId;
	}

}
