package org.irdresearch.tbreach.shared.model;

// Generated Aug 29, 2012 9:08:23 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * NonSuspect generated by hbm2java
 */
public class NonSuspect implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 410414147536460778L;
	private Integer				nonSuspectId;
	private String				patientId;
	private String				gpid;
	private String				chwid;
	private Date				dateEntered;
	private String				firstName;
	private String				lastName;
	private Integer				age;
	private Character			gender;
	private String				diabetesHistory;
	private String				diabetesFamilyHistory;
	private String				lungDiseaseHistory;
	private String				lungDiseaseFamilyHistory;
	private String				currentlySmoking;
	private String				smokingHistory;
	private String				usedNarcotics;

	public NonSuspect()
	{
	}

	public NonSuspect(String patientId)
	{
		this.patientId = patientId;
	}

	public NonSuspect(String patientId, String gpid, String chwid, Date dateEntered, String firstName, String lastName, Integer age,
			Character gender, String diabetesHistory, String diabetesFamilyHistory, String lungDiseaseHistory, String lungDiseaseFamilyHistory,
			String currentlySmoking, String smokingHistory, String usedNarcotics)
	{
		this.patientId = patientId;
		this.gpid = gpid;
		this.chwid = chwid;
		this.dateEntered = dateEntered;
		this.firstName = firstName;
		this.lastName = lastName;
		this.age = age;
		this.gender = gender;
		this.diabetesHistory = diabetesHistory;
		this.diabetesFamilyHistory = diabetesFamilyHistory;
		this.lungDiseaseHistory = lungDiseaseHistory;
		this.lungDiseaseFamilyHistory = lungDiseaseFamilyHistory;
		this.currentlySmoking = currentlySmoking;
		this.smokingHistory = smokingHistory;
		this.usedNarcotics = usedNarcotics;
	}

	public Integer getNonSuspectId()
	{
		return this.nonSuspectId;
	}

	public void setNonSuspectId(Integer nonSuspectId)
	{
		this.nonSuspectId = nonSuspectId;
	}

	public String getPatientId()
	{
		return this.patientId;
	}

	public void setPatientId(String patientId)
	{
		this.patientId = patientId;
	}

	public String getGpid()
	{
		return this.gpid;
	}

	public void setGpid(String gpid)
	{
		this.gpid = gpid;
	}

	public String getChwid()
	{
		return this.chwid;
	}

	public void setChwid(String chwid)
	{
		this.chwid = chwid;
	}

	public Date getDateEntered()
	{
		return this.dateEntered;
	}

	public void setDateEntered(Date dateEntered)
	{
		this.dateEntered = dateEntered;
	}

	public String getFirstName()
	{
		return this.firstName;
	}

	public void setFirstName(String firstName)
	{
		this.firstName = firstName;
	}

	public String getLastName()
	{
		return this.lastName;
	}

	public void setLastName(String lastName)
	{
		this.lastName = lastName;
	}

	public Integer getAge()
	{
		return this.age;
	}

	public void setAge(Integer age)
	{
		this.age = age;
	}

	public Character getGender()
	{
		return this.gender;
	}

	public void setGender(Character gender)
	{
		this.gender = gender;
	}

	public String getDiabetesHistory()
	{
		return this.diabetesHistory;
	}

	public void setDiabetesHistory(String diabetesHistory)
	{
		this.diabetesHistory = diabetesHistory;
	}

	public String getDiabetesFamilyHistory()
	{
		return this.diabetesFamilyHistory;
	}

	public void setDiabetesFamilyHistory(String diabetesFamilyHistory)
	{
		this.diabetesFamilyHistory = diabetesFamilyHistory;
	}

	public String getLungDiseaseHistory()
	{
		return this.lungDiseaseHistory;
	}

	public void setLungDiseaseHistory(String lungDiseaseHistory)
	{
		this.lungDiseaseHistory = lungDiseaseHistory;
	}

	public String getLungDiseaseFamilyHistory()
	{
		return this.lungDiseaseFamilyHistory;
	}

	public void setLungDiseaseFamilyHistory(String lungDiseaseFamilyHistory)
	{
		this.lungDiseaseFamilyHistory = lungDiseaseFamilyHistory;
	}

	public String getCurrentlySmoking()
	{
		return this.currentlySmoking;
	}

	public void setCurrentlySmoking(String currentlySmoking)
	{
		this.currentlySmoking = currentlySmoking;
	}

	public String getSmokingHistory()
	{
		return this.smokingHistory;
	}

	public void setSmokingHistory(String smokingHistory)
	{
		this.smokingHistory = smokingHistory;
	}

	public String getUsedNarcotics()
	{
		return this.usedNarcotics;
	}

	public void setUsedNarcotics(String usedNarcotics)
	{
		this.usedNarcotics = usedNarcotics;
	}

	public String toString()
	{
		return nonSuspectId + ", " + patientId + ", " + gpid + ", " + chwid + ", " + dateEntered + ", " + firstName + ", " + lastName + ", " + age
				+ ", " + gender + ", " + diabetesHistory + ", " + diabetesFamilyHistory + ", " + lungDiseaseHistory + ", " + lungDiseaseFamilyHistory
				+ ", " + currentlySmoking + ", " + smokingHistory + ", " + usedNarcotics;
	}
}
