package org.irdresearch.tbreach.shared.model;

// default package
// Generated Dec 21, 2010 3:45:59 PM by Hibernate Tools 3.4.0.Beta1

/**
 * SetupIncentive generated by hbm2java
 */
public class SetupIncentive implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 4038237180413387875L;
	private String				incentiveId;
	private String				incentiveName;
	private String				beneficiaryGroup;
	private double				amount;
	private String				currency;
	private String				scheduleId;
	private String				detail;

	public SetupIncentive()
	{
		// Not implemented
	}

	public SetupIncentive(String incentiveId, String incentiveName, String beneficiaryGroup, double amount, String currency, String scheduleId)
	{
		this.incentiveId = incentiveId;
		this.incentiveName = incentiveName;
		this.beneficiaryGroup = beneficiaryGroup;
		this.amount = amount;
		this.currency = currency;
		this.scheduleId = scheduleId;
	}

	public SetupIncentive(String incentiveId, String incentiveName, String beneficiaryGroup, double amount, String currency, String scheduleId,
			String detail)
	{
		this.incentiveId = incentiveId;
		this.incentiveName = incentiveName;
		this.beneficiaryGroup = beneficiaryGroup;
		this.amount = amount;
		this.currency = currency;
		this.scheduleId = scheduleId;
		this.detail = detail;
	}

	public String getIncentiveId()
	{
		return this.incentiveId;
	}

	public void setIncentiveId(String incentiveId)
	{
		this.incentiveId = incentiveId;
	}

	public String getIncentiveName()
	{
		return this.incentiveName;
	}

	public void setIncentiveName(String incentiveName)
	{
		this.incentiveName = incentiveName;
	}

	public String getBeneficiaryGroup()
	{
		return this.beneficiaryGroup;
	}

	public void setBeneficiaryGroup(String beneficiaryGroup)
	{
		this.beneficiaryGroup = beneficiaryGroup;
	}

	public double getAmount()
	{
		return this.amount;
	}

	public void setAmount(double amount)
	{
		this.amount = amount;
	}

	public String getCurrency()
	{
		return this.currency;
	}

	public void setCurrency(String currency)
	{
		this.currency = currency;
	}

	public String getScheduleId()
	{
		return this.scheduleId;
	}

	public void setScheduleId(String scheduleId)
	{
		this.scheduleId = scheduleId;
	}

	public String getDetail()
	{
		return this.detail;
	}

	public void setDetail(String detail)
	{
		this.detail = detail;
	}

	@Override
	public String toString()
	{
		return incentiveId + ", " + incentiveName + ", " + beneficiaryGroup + ", " + amount + ", " + currency + ", " + scheduleId + ", " + detail;
	}

}
