DROP TABLE IF EXISTS `ilms_acc_reg`;
DROP TABLE IF EXISTS `ilms_brn_reg`;
DROP TABLE IF EXISTS `ilms_dues_rec`;
DROP TABLE IF EXISTS `ilms_bs_master`;
DROP TABLE IF EXISTS `ilms_bs_trans`;
DROP TABLE IF EXISTS `ilms_dep_reg`;
DROP TABLE IF EXISTS `ilms_desig_reg`;
DROP TABLE IF EXISTS `ilms_doc_bs`;
DROP TABLE IF EXISTS ``;
DROP TABLE IF EXISTS ``;
DROP TABLE IF EXISTS ``;
DROP TABLE IF EXISTS ``;
CREATE TABLE `` ( `column1` varchar(20) NOT NULL, `column2` varchar(10) NOT NULL);
CREATE TABLE `` ( `column1` varchar(20) NOT NULL, `column2` varchar(10) NOT NULL);
CREATE TABLE `` ( `column1` varchar(20) NOT NULL, `column2` varchar(10) NOT NULL);
CREATE TABLE `` ( `column1` varchar(20) NOT NULL, `column2` varchar(10) NOT NULL);
CREATE TABLE `` ( `column1` varchar(20) NOT NULL, `column2` varchar(10) NOT NULL);
CREATE TABLE `` ( `column1` varchar(20) NOT NULL, `column2` varchar(10) NOT NULL);
CREATE TABLE `` ( `column1` varchar(20) NOT NULL, `column2` varchar(10) NOT NULL);
CREATE TABLE `` ( `column1` varchar(20) NOT NULL, `column2` varchar(10) NOT NULL);
CREATE TABLE `` ( `column1` varchar(20) NOT NULL, `column2` varchar(10) NOT NULL);
CREATE TABLE `` ( `column1` varchar(20) NOT NULL, `column2` varchar(10) NOT NULL);