package com.ihsinformatics.tbr3fieldmonitoring.shared.model;

// Generated Nov 14, 2012 11:36:54 AM by Hibernate Tools 3.4.0.Beta1

/**
 * Location generated by hbm2java
 */
public class Location implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = -991576038022232033L;
	private String locationId;
	private String locationName;
	private String locationType;
	private String address1;
	private String address2;
	private String address3;
	private String address4;
	private String city;
	private String state;
	private String country;
	private String region;
	private Float latitude;
	private Float longitude;
	private String phone;
	private String mobile;
	private String email;
	private String fax;
	private String otherPhone;
	private String otherMobile;
	private String otherEmail;
	private String otherFax;

	public Location()
	{
	}

	public Location(String locationId, String locationName, String locationType)
	{
		this.locationId = locationId;
		this.locationName = locationName;
		this.locationType = locationType;
	}

	public Location(String locationId, String locationName,
			String locationType, String address1, String address2,
			String address3, String address4, String city, String state,
			String country, String region, Float latitude, Float longitude,
			String phone, String mobile, String email, String fax,
			String otherPhone, String otherMobile, String otherEmail,
			String otherFax)
	{
		this.locationId = locationId;
		this.locationName = locationName;
		this.locationType = locationType;
		this.address1 = address1;
		this.address2 = address2;
		this.address3 = address3;
		this.address4 = address4;
		this.city = city;
		this.state = state;
		this.country = country;
		this.region = region;
		this.latitude = latitude;
		this.longitude = longitude;
		this.phone = phone;
		this.mobile = mobile;
		this.email = email;
		this.fax = fax;
		this.otherPhone = otherPhone;
		this.otherMobile = otherMobile;
		this.otherEmail = otherEmail;
		this.otherFax = otherFax;
	}

	public String getLocationId()
	{
		return this.locationId;
	}

	public void setLocationId(String locationId)
	{
		this.locationId = locationId;
	}

	public String getLocationName()
	{
		return this.locationName;
	}

	public void setLocationName(String locationName)
	{
		this.locationName = locationName;
	}

	public String getLocationType()
	{
		return this.locationType;
	}

	public void setLocationType(String locationType)
	{
		this.locationType = locationType;
	}

	public String getAddress1()
	{
		return this.address1;
	}

	public void setAddress1(String address1)
	{
		this.address1 = address1;
	}

	public String getAddress2()
	{
		return this.address2;
	}

	public void setAddress2(String address2)
	{
		this.address2 = address2;
	}

	public String getAddress3()
	{
		return this.address3;
	}

	public void setAddress3(String address3)
	{
		this.address3 = address3;
	}

	public String getAddress4()
	{
		return this.address4;
	}

	public void setAddress4(String address4)
	{
		this.address4 = address4;
	}

	public String getCity()
	{
		return this.city;
	}

	public void setCity(String city)
	{
		this.city = city;
	}

	public String getState()
	{
		return this.state;
	}

	public void setState(String state)
	{
		this.state = state;
	}

	public String getCountry()
	{
		return this.country;
	}

	public void setCountry(String country)
	{
		this.country = country;
	}

	public String getRegion()
	{
		return this.region;
	}

	public void setRegion(String region)
	{
		this.region = region;
	}

	public Float getLatitude()
	{
		return this.latitude;
	}

	public void setLatitude(Float latitude)
	{
		this.latitude = latitude;
	}

	public Float getLongitude()
	{
		return this.longitude;
	}

	public void setLongitude(Float longitude)
	{
		this.longitude = longitude;
	}

	public String getPhone()
	{
		return this.phone;
	}

	public void setPhone(String phone)
	{
		this.phone = phone;
	}

	public String getMobile()
	{
		return this.mobile;
	}

	public void setMobile(String mobile)
	{
		this.mobile = mobile;
	}

	public String getEmail()
	{
		return this.email;
	}

	public void setEmail(String email)
	{
		this.email = email;
	}

	public String getFax()
	{
		return this.fax;
	}

	public void setFax(String fax)
	{
		this.fax = fax;
	}

	public String getOtherPhone()
	{
		return this.otherPhone;
	}

	public void setOtherPhone(String otherPhone)
	{
		this.otherPhone = otherPhone;
	}

	public String getOtherMobile()
	{
		return this.otherMobile;
	}

	public void setOtherMobile(String otherMobile)
	{
		this.otherMobile = otherMobile;
	}

	public String getOtherEmail()
	{
		return this.otherEmail;
	}

	public void setOtherEmail(String otherEmail)
	{
		this.otherEmail = otherEmail;
	}

	public String getOtherFax()
	{
		return this.otherFax;
	}

	public void setOtherFax(String otherFax)
	{
		this.otherFax = otherFax;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		return locationId + ", " + locationName + ", " + locationType + ", "
				+ address1 + ", " + address2 + ", " + address3 + ", "
				+ address4 + ", " + city + ", " + state + ", " + country + ", "
				+ region + ", " + latitude + ", " + longitude + ", " + phone
				+ ", " + mobile + ", " + email + ", " + fax + ", " + otherPhone
				+ ", " + otherMobile + ", " + otherEmail + ", " + otherFax;
	}

}
