package com.ihsinformatics.tbr3fieldmonitoring.shared.model;

// Generated Nov 21, 2012 12:51:56 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * SmsLog generated by hbm2java
 */
public class SmsLog implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = -2529850426539305169L;
	private Integer logId;
	private String ruleId;
	private String status;
	private String cancellationReason;
	private Date dateDue;
	private Date dateSent;
	private String recipientReferenceTable;
	private String recipientReferenceColumn;
	private String recipientId;
	private String recipientNumber;
	private String text;
	private String referenceNumber;
	private Date dateCreated;
	private String creatorId;
	private String description;

	public SmsLog()
	{
	}

	public SmsLog(String referenceNumber)
	{
		this.referenceNumber = referenceNumber;
	}

	public SmsLog(String ruleId, String status, String cancellationReason,
			Date dateDue, Date dateSent, String recipientReferenceTable,
			String recipientReferenceColumn, String recipientId,
			String recipientNumber, String text, String referenceNumber,
			Date dateCreated, String creatorId, String description)
	{
		this.ruleId = ruleId;
		this.status = status;
		this.cancellationReason = cancellationReason;
		this.dateDue = dateDue;
		this.dateSent = dateSent;
		this.recipientReferenceTable = recipientReferenceTable;
		this.recipientReferenceColumn = recipientReferenceColumn;
		this.recipientId = recipientId;
		this.recipientNumber = recipientNumber;
		this.text = text;
		this.referenceNumber = referenceNumber;
		this.dateCreated = dateCreated;
		this.creatorId = creatorId;
		this.description = description;
	}

	public Integer getLogId()
	{
		return this.logId;
	}

	public void setLogId(Integer logId)
	{
		this.logId = logId;
	}

	public String getRuleId()
	{
		return this.ruleId;
	}

	public void setRuleId(String ruleId)
	{
		this.ruleId = ruleId;
	}

	public String getStatus()
	{
		return this.status;
	}

	public void setStatus(String status)
	{
		this.status = status;
	}

	public String getCancellationReason()
	{
		return this.cancellationReason;
	}

	public void setCancellationReason(String cancellationReason)
	{
		this.cancellationReason = cancellationReason;
	}

	public Date getDateDue()
	{
		return this.dateDue;
	}

	public void setDateDue(Date dateDue)
	{
		this.dateDue = dateDue;
	}

	public Date getDateSent()
	{
		return this.dateSent;
	}

	public void setDateSent(Date dateSent)
	{
		this.dateSent = dateSent;
	}

	public String getRecipientReferenceTable()
	{
		return this.recipientReferenceTable;
	}

	public void setRecipientReferenceTable(String recipientReferenceTable)
	{
		this.recipientReferenceTable = recipientReferenceTable;
	}

	public String getRecipientReferenceColumn()
	{
		return this.recipientReferenceColumn;
	}

	public void setRecipientReferenceColumn(String recipientReferenceColumn)
	{
		this.recipientReferenceColumn = recipientReferenceColumn;
	}

	public String getRecipientId()
	{
		return this.recipientId;
	}

	public void setRecipientId(String recipientId)
	{
		this.recipientId = recipientId;
	}

	public String getRecipientNumber()
	{
		return this.recipientNumber;
	}

	public void setRecipientNumber(String recipientNumber)
	{
		this.recipientNumber = recipientNumber;
	}

	public String getText()
	{
		return this.text;
	}

	public void setText(String text)
	{
		this.text = text;
	}

	public String getReferenceNumber()
	{
		return this.referenceNumber;
	}

	public void setReferenceNumber(String referenceNumber)
	{
		this.referenceNumber = referenceNumber;
	}

	public Date getDateCreated()
	{
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated)
	{
		this.dateCreated = dateCreated;
	}

	public String getCreatorId()
	{
		return this.creatorId;
	}

	public void setCreatorId(String creatorId)
	{
		this.creatorId = creatorId;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		return logId + ", " + ruleId + ", " + status + ", "
				+ cancellationReason + ", " + dateDue + ", " + dateSent + ", "
				+ recipientReferenceTable + ", " + recipientReferenceColumn
				+ ", " + recipientId + ", " + recipientNumber + ", " + text
				+ ", " + referenceNumber + ", " + dateCreated + ", "
				+ creatorId + ", " + description;
	}
}
