package com.ihsinformatics.tbr3fieldmonitoring.shared.model;

// Generated Nov 21, 2012 5:30:53 PM by Hibernate Tools 3.4.0.Beta1

/**
 * SmsRule generated by hbm2java
 */
public class SmsRule implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 7093239894552063672L;
	private String ruleId;
	private String ruleName;
	private String type;
	private String rule;
	private Boolean isEnabled;
	private String referenceTable;
	private String referenceColumn;
	private Integer startDay;
	private Integer iterations;
	private Integer smsInterval;
	private String description;

	public SmsRule()
	{
	}

	public SmsRule(String ruleId)
	{
		this.ruleId = ruleId;
	}

	public SmsRule(String ruleId, String ruleName, String type, String rule,
			Boolean isEnabled, String referenceTable, String referenceColumn,
			Integer startDay, Integer iterations, Integer smsInterval,
			Integer endDay, String description, Integer serviceRunupMinutes)
	{
		this.ruleId = ruleId;
		this.ruleName = ruleName;
		this.type = type;
		this.rule = rule;
		this.isEnabled = isEnabled;
		this.referenceTable = referenceTable;
		this.referenceColumn = referenceColumn;
		this.startDay = startDay;
		this.iterations = iterations;
		this.smsInterval = smsInterval;
		this.description = description;
	}

	public String getRuleId()
	{
		return this.ruleId;
	}

	public void setRuleId(String ruleId)
	{
		this.ruleId = ruleId;
	}

	public String getRuleName()
	{
		return this.ruleName;
	}

	public void setRuleName(String ruleName)
	{
		this.ruleName = ruleName;
	}

	public String getType()
	{
		return this.type;
	}

	public void setType(String type)
	{
		this.type = type;
	}

	public String getRule()
	{
		return this.rule;
	}

	public void setRule(String rule)
	{
		this.rule = rule;
	}

	public Boolean getIsEnabled()
	{
		return this.isEnabled;
	}

	public void setIsEnabled(Boolean isEnabled)
	{
		this.isEnabled = isEnabled;
	}

	public String getReferenceTable()
	{
		return this.referenceTable;
	}

	public void setReferenceTable(String referenceTable)
	{
		this.referenceTable = referenceTable;
	}

	public String getReferenceColumn()
	{
		return this.referenceColumn;
	}

	public void setReferenceColumn(String referenceColumn)
	{
		this.referenceColumn = referenceColumn;
	}

	public Integer getStartDay()
	{
		return this.startDay;
	}

	public void setStartDay(Integer startDay)
	{
		this.startDay = startDay;
	}

	public Integer getIterations()
	{
		return this.iterations;
	}

	public void setIterations(Integer iterations)
	{
		this.iterations = iterations;
	}

	public Integer getSmsInterval()
	{
		return this.smsInterval;
	}

	public void setSmsInterval(Integer smsInterval)
	{
		this.smsInterval = smsInterval;
	}

	public String getDescription()
	{
		return this.description;
	}

	public void setDescription(String description)
	{
		this.description = description;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		return ruleId + ", " + ruleName + ", " + type + ", " + rule + ", "
				+ isEnabled + ", " + referenceTable + ", " + referenceColumn
				+ ", " + startDay + ", " + iterations + ", " + smsInterval
				+ ", " + description;
	}
}
