package com.ihsinformatics.tbr3fieldmonitoring.shared.model;

// Generated Nov 17, 2012 3:02:56 PM by Hibernate Tools 3.4.0.Beta1

import java.util.Date;

/**
 * Visit generated by hbm2java
 */
public class Visit implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 8308799265129812458L;
	private Integer visitNo;
	private String patientId;
	private String visitPurpose;
	private Boolean diseaseConfirmed;
	private Date visitDate;

	public Visit()
	{
		// Not implemented
	}

	public Visit(String patientId, String visitPurpose)
	{
		this.patientId = patientId;
		this.visitPurpose = visitPurpose;
	}

	public Visit(String patientId, String visitPurpose,
			Boolean disease_confirmed, Date visitDate)
	{
		this.patientId = patientId;
		this.visitPurpose = visitPurpose;
		this.diseaseConfirmed = disease_confirmed;
		this.visitDate = visitDate;
	}

	public Integer getVisitNo()
	{
		return this.visitNo;
	}

	public void setVisitNo(Integer visitNo)
	{
		this.visitNo = visitNo;
	}

	public String getPatientId()
	{
		return this.patientId;
	}

	public void setPatientId(String patientId)
	{
		this.patientId = patientId;
	}

	public String getVisitPurpose()
	{
		return this.visitPurpose;
	}

	public void setVisitPurpose(String visitPurpose)
	{
		this.visitPurpose = visitPurpose;
	}

	public Boolean getDiseaseConfirmed()
	{
		return this.diseaseConfirmed;
	}

	public void setDiseaseConfirmed(Boolean disease_confirmed)
	{
		this.diseaseConfirmed = disease_confirmed;
	}

	public Date getVisitDate()
	{
		return this.visitDate;
	}

	public void setVisitDate(Date visitDate)
	{
		this.visitDate = visitDate;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString()
	{
		return visitNo + ", " + patientId + ", " + visitPurpose + ", "
				+ diseaseConfirmed + ", " + visitDate;
	}
}
